import type { MenuItem } from "./types";
import placeholder from "../public/placeholder.svg";
export const categories = [
    { id: "all", name: "Todos" },
    { id: "cafe", name: "Cafés" },
    { id: "cappuccino", name: "Cappuccino" },
    { id: "fondue", name: "Fondue" },
    { id: "lanches", name: "Lanches" },
    { id: "bebidas", name: "Outras Bebidas" },
];

export const menuItems: MenuItem[] = [
    // Cafés
    {
        id: "1",
        name: "Espresso - Pequeno",
        description: "Café espresso clássico, servido com um chocolate",
        price: 9.9,
        priceMember: 7.9,
        category: "cafe",
        image: "https://www.bongusto.ind.br/wp-content/uploads/2023/06/mockup-galeria-cafe-espresso-classico.jpg",
    },
    {
        id: "2",
        name: "Espresso - Duplo",
        description: "Café espresso clássico, servido com um chocolate",
        price: 14.9,
        priceMember: 12.9,
        category: "cafe",
        image: "https://thumbs.dreamstime.com/b/caf%C3%A9-expresso-duplo-fresco-e-em-mesa-de-madeira-269579364.jpg",
    },
    {
        id: "3",
        name: "Espresso - Filtrado",
        description: "Café espresso clássico, servido com um chocolate",
        price: 11.9,
        priceMember: 9.9,
        category: "cafe",
        image: "https://www.bongusto.ind.br/wp-content/uploads/2023/06/mockup-galeria-cafe-espresso-classico.jpg",
    },
    {
        id: "4",
        name: "Latte - Pequeno",
        description: "Café Latte clássico, servido com um chocolate",
        price: 16.9,
        priceMember: 14.9,
        category: "cafe",
        image: "https://assets.olaclick.app/companies/products/images/800/9e7d443e-c032-46b0-af5a-eafa30724692.jpg",
    },
    {
        id: "5",
        name: "Latte - Grande",
        description: "Café Latte clássico, servido com um chocolate",
        price: 21.9,
        priceMember: 18.9,
        category: "cafe",
        image: "https://assets.olaclick.app/companies/products/images/800/9e7d443e-c032-46b0-af5a-eafa30724692.jpg",
    },
    {
        id: "6",
        name: "Chá",
        description: "Conferir disponibilidade de sabores",
        price: 12.9,
        priceMember: 10.9,
        category: "bebidas",
        image: "https://totalpass.com/wp-content/uploads/2025/08/cha.jpg",
    },
    {
        id: "7",
        name: "Água Mineral",
        description: "Conferir disponibilidade de sabores",
        price: 6.9,
        priceMember: 5.9,
        category: "bebidas",
        image: "https://s2-receitas.glbimg.com/32CCRFrcIh4_QHAROTnyg9E8nzg=/0x0:1000x673/984x0/smart/filters:strip_icc()/i.s3.glbimg.com/v1/AUTH_1f540e0b94d8437dbbc39d567a1dee68/internal_photos/bs/2023/l/c/Dru9B2SZSxiPS7XjUgBw/agua-com-gas-hidrata-faz-mal-nutricionista-esclarece.jpg",
    },
    {
        id: "8",
        name: "Água Mineral com Gás",
        description: "Conferir disponibilidade de sabores",
        price: 7.9,
        priceMember: 6.9,
        category: "bebidas",
        image: "https://s2-receitas.glbimg.com/32CCRFrcIh4_QHAROTnyg9E8nzg=/0x0:1000x673/984x0/smart/filters:strip_icc()/i.s3.glbimg.com/v1/AUTH_1f540e0b94d8437dbbc39d567a1dee68/internal_photos/bs/2023/l/c/Dru9B2SZSxiPS7XjUgBw/agua-com-gas-hidrata-faz-mal-nutricionista-esclarece.jpg",
    },
    {
        id: "9",
        name: "Cappuccino Tradicional - Pequeno",
        description: "Cappuccino tradicional, servido com um chocolate",
        price: 18.9,
        priceMember: 15.9,
        category: "cappuccino",
        image: "https://www.bongusto.ind.br/wp-content/uploads/2023/06/mockup-galeria-capuccino-tradicional-xicara.jpg",
    },
    {
        id: "10",
        name: "Cappuccino Tradicional - Grande",
        description: "Cappuccino tradicional, servido com um chocolate",
        price: 23.9,
        priceMember: 20.9,
        category: "cappuccino",
        image: "https://www.mococa.com.br/wp-content/uploads/2022/07/Cappuccino-com-Mocoquinha_4-scaled.jpg",
    },
    {
        id: "11",
        name: "Cappuccino LaCreme - Pequeno",
        description: "Preparado com trufa LaCreme ao leite",
        price: 22.9,
        priceMember: 19.9,
        category: "cappuccino",
        image: "https://cdn.uairango.com/produtos/49ad369c2f5266145f0da500900fafaa.png",
    },
    {
        id: "12",
        name: "Cappuccino LaCreme - Grande",
        description: "Preparado com trufa LaCreme ao leite",
        price: 27.9,
        priceMember: 24.9,
        category: "cappuccino",
        image: "https://cdn.uairango.com/produtos/49ad369c2f5266145f0da500900fafaa.png",
    },
    {
        id: "13",
        name: "Cappuccino Bendito Cacau - Pequeno",
        description: "Preparado com tablete Bendito Cacau 55%",
        price: 24.9,
        priceMember: 21.9,
        category: "cappuccino",
        image: "https://scontent.ffec20-1.fna.fbcdn.net/v/t39.30808-6/506395789_10162268448857535_6732829935748374464_n.jpg?stp=dst-jpg_s1080x2048_tt6&_nc_cat=109&ccb=1-7&_nc_sid=13d280&_nc_ohc=CDjL4h38kJoQ7kNvwGTCLFN&_nc_oc=AdrPPSYYOXvSKPkgxxE_g9WojYsg3Ztba4D09vPqwDVPZ36W2Y0cJw_i8JBJwWlHr9SETfGDsHBDEYWQBHxuOHal&_nc_zt=23&_nc_ht=scontent.ffec20-1.fna&_nc_gid=LxpDC9csq7q9rHImkMqyyg&_nc_ss=7b289&oh=00_Af7nXDVVxsETGQYAPHv7xoFzKqq__qm7ogXlkpEh2rcwpQ&oe=69FAA766",
    },
    {
        id: "14",
        name: "Cappuccino Bendito Cacau - Grande",
        description: "Preparado com tablete Bendito Cacau 55%",
        price: 29.9,
        priceMember: 26.9,
        category: "cappuccino",
        image: "https://scontent.ffec20-1.fna.fbcdn.net/v/t39.30808-6/506395789_10162268448857535_6732829935748374464_n.jpg?stp=dst-jpg_s1080x2048_tt6&_nc_cat=109&ccb=1-7&_nc_sid=13d280&_nc_ohc=CDjL4h38kJoQ7kNvwGTCLFN&_nc_oc=AdrPPSYYOXvSKPkgxxE_g9WojYsg3Ztba4D09vPqwDVPZ36W2Y0cJw_i8JBJwWlHr9SETfGDsHBDEYWQBHxuOHal&_nc_zt=23&_nc_ht=scontent.ffec20-1.fna&_nc_gid=LxpDC9csq7q9rHImkMqyyg&_nc_ss=7b289&oh=00_Af7nXDVVxsETGQYAPHv7xoFzKqq__qm7ogXlkpEh2rcwpQ&oe=69FAA766",
    },
];

// export const menuItems: MenuItem[] = [
//     // Lanches
//     {
//         id: "1",
//         name: "X-Burguer Clássico",
//         description:
//             "Pão, hambúrguer 180g, queijo, alface, tomate e molho especial",
//         price: 25.9,
//         category: "lanches",
//         image: "https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=400&h=300&fit=crop",
//     },
//     {
//         id: "2",
//         name: "X-Bacon",
//         description:
//             "Pão, hambúrguer 180g, queijo, bacon crocante, alface e molho barbecue",
//         price: 29.9,
//         category: "lanches",
//         image: "https://images.unsplash.com/photo-1553979459-d2229ba7433b?w=400&h=300&fit=crop",
//     },
//     {
//         id: "3",
//         name: "X-Tudo",
//         description:
//             "Pão, 2 hambúrgueres, queijo duplo, bacon, ovo, presunto, alface, tomate e molho",
//         price: 38.9,
//         category: "lanches",
//         image: "https://images.unsplash.com/photo-1594212699903-ec8a3eca50f5?w=400&h=300&fit=crop",
//     },
//     {
//         id: "4",
//         name: "Frango Crispy",
//         description:
//             "Pão brioche, frango empanado crocante, coleslaw e maionese de ervas",
//         price: 27.9,
//         category: "lanches",
//         image: "https://images.unsplash.com/photo-1606755962773-d324e0a13086?w=400&h=300&fit=crop",
//     },
//     // Pizzas
//     {
//         id: "5",
//         name: "Pizza Margherita",
//         description: "Molho de tomate, mussarela, tomate e manjericão fresco",
//         price: 45.9,
//         category: "pizzas",
//         image: "https://images.unsplash.com/photo-1604068549290-dea0e4a305ca?w=400&h=300&fit=crop",
//     },
//     {
//         id: "6",
//         name: "Pizza Calabresa",
//         description: "Molho de tomate, mussarela, calabresa fatiada e cebola",
//         price: 49.9,
//         category: "pizzas",
//         image: "https://images.unsplash.com/photo-1628840042765-356cda07504e?w=400&h=300&fit=crop",
//     },
//     {
//         id: "7",
//         name: "Pizza Quatro Queijos",
//         description:
//             "Molho de tomate, mussarela, provolone, parmesão e gorgonzola",
//         price: 54.9,
//         category: "pizzas",
//         image: "https://images.unsplash.com/photo-1513104890138-7c749659a591?w=400&h=300&fit=crop",
//     },
//     // Porções
//     {
//         id: "8",
//         name: "Batata Frita",
//         description: "Porção de batatas fritas crocantes com sal e orégano",
//         price: 18.9,
//         category: "porcoes",
//         image: "https://images.unsplash.com/photo-1573080496219-bb080dd4f877?w=400&h=300&fit=crop",
//     },
//     {
//         id: "9",
//         name: "Onion Rings",
//         description: "Anéis de cebola empanados e fritos até ficarem dourados",
//         price: 22.9,
//         category: "porcoes",
//         image: "https://images.unsplash.com/photo-1639024471283-03518883512d?w=400&h=300&fit=crop",
//     },
//     {
//         id: "10",
//         name: "Nuggets",
//         description: "10 unidades de nuggets de frango crocantes",
//         price: 24.9,
//         category: "porcoes",
//         image: "https://images.unsplash.com/photo-1562967914-608f82629710?w=400&h=300&fit=crop",
//     },
//     // Bebidas
//     {
//         id: "11",
//         name: "Refrigerante Lata",
//         description: "Coca-Cola, Guaraná ou Fanta - 350ml",
//         price: 6.9,
//         category: "bebidas",
//         image: "https://images.unsplash.com/photo-1622483767028-3f66f32aef97?w=400&h=300&fit=crop",
//     },
//     {
//         id: "12",
//         name: "Suco Natural",
//         description: "Laranja, limão, maracujá ou abacaxi - 500ml",
//         price: 12.9,
//         category: "bebidas",
//         image: "https://images.unsplash.com/photo-1600271886742-f049cd451bba?w=400&h=300&fit=crop",
//     },
//     {
//         id: "13",
//         name: "Milkshake",
//         description: "Chocolate, morango ou ovomaltine - 400ml",
//         price: 16.9,
//         category: "bebidas",
//         image: "https://images.unsplash.com/photo-1572490122747-3968b75cc699?w=400&h=300&fit=crop",
//     },
//     // Sobremesas
//     {
//         id: "14",
//         name: "Brownie com Sorvete",
//         description: "Brownie de chocolate quentinho com sorvete de creme",
//         price: 19.9,
//         category: "sobremesas",
//         image: "https://images.unsplash.com/photo-1564355808539-22fda35bed7e?w=400&h=300&fit=crop",
//     },
//     {
//         id: "15",
//         name: "Petit Gateau",
//         description: "Bolo de chocolate com interior cremoso e sorvete",
//         price: 22.9,
//         category: "sobremesas",
//         image: "https://images.unsplash.com/photo-1606313564200-e75d5e30476c?w=400&h=300&fit=crop",
//     },
// ];
